[package]
name = "self_update"
version = "0.8.0"
description = "Self updates for standalone executables"
repository = "https://github.com/jaemk/self_update"
keywords = ["update", "upgrade", "download", "release"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"
authors = ["James Kominick <james@kominick.com>"]
exclude = ["/ci/*", ".travis.yml", "appveyor.yml"]
edition = "2018"

[dependencies]
serde_json = "1"
reqwest = "0.9"
tempdir = "0.3"
flate2 = "1"
tar = "0.4"
semver = "0.9"
hyper-old-types = "0.11.0"
zip = "0.5.0"
either = "1.5.0"
indicatif = "0.11.0"
quick-xml = "0.17.2"
regex = "1.3.1"
